### ISSUE TITLE
Золотой песок

### ISSUE THREAD

**Issue by YogurtTheHorse** [yegorf1/RogueBot#101]
Описание: Увеличивают количество получаемого золота в два раза на 10 ходов
Потом они рассыпаются
Цена: 700

**Comment by KaneNOD** [comment]
как сильно они увеличивают количество золота?

**Comment by thekiba** [comment]
> Описание: Увеличивают количество получаемого золота **в два раза** на 10 ходов

**Comment by KaneNOD** [comment]
я был слеп
