### ISSUE TITLE
Сделать заклинания и привязать к ним ману

### ISSUE THREAD

**Issue by KaneNOD** [yegorf1/RogueBot#102]

**Comment by YogurtTheHorse** [comment]
Еще наверное стоит брать ману за маг. урон

**Comment by KaneNOD** [comment]
разумеется

**Comment by Isuaven** [comment]
> Еще наверное стоит брать ману за маг. урон

Тогда вводите стамину, которая будет тратиться на физ атаки. Для баланса

**Comment by thekiba** [comment]
> Тогда вводите стамину, которая будет тратиться на физ атаки. Для баланса

Тогда сразу вопрос, как ее восстанавливать?

**Comment by YogurtTheHorse** [comment]
Буддой

**Comment by thekiba** [comment]
А во время боя что делать?

Вот я на боссе и закончилась стамина. Что должен сделать игрок, чтобы ее восстановить?

**Comment by YogurtTheHorse** [comment]
Зелье добавить соответствующее

**Comment by thekiba** [comment]
Что с этим таском? Какой статус?

**Comment by YogurtTheHorse** [comment]
В ящике

**Comment by kuleshov-aleksei** [comment]
Thekiba, я сделал, но надо найти и пофиксить ошибку

**Comment by thekiba** [comment]
@Encamy отправь сюда ссылку на pull-request

**Comment by YogurtTheHorse** [comment]
> @Encamy отправь сюда ссылку на pull-request

#162
