### ISSUE TITLE
Сделать твиттербот с жизнью боссов

### ISSUE THREAD

**Issue by KaneNOD** [yegorf1/RogueBot#103]
Берём любого "харизматичного", запоминающегося моба или босса. А ещё лучше, создаём под это дело нового, заточенного. 
1. Пишем апи-бот для свитера
2. Транслируем туда "жизнь моба", якобы он пишет твиты
3. Всё это сопровождается шутеечками в корпоративном стиле 
3.1. Например "Зашёл %NAME%, хотел соли одолжить. Так слово за слово, я получил по лицу. Ещё и %GOLD% золота должен остался." (моб умер от плеера)
3.2. "Какой-то парень пронёсся мимо с криками "АЫААА", потом развернулся и влетел в меня. Я такого не стерпел."  (игрок умер от моба (шуток получше за 1 минуту я не придумал))
4. ?????
5. Профит!

идея владислава

**Comment by YogurtTheHorse** [comment]
Перенесоим в секретные разработки
