### ISSUE TITLE
Лепрекон перезапускает сюжетные комнаты

### ISSUE THREAD

**Issue by KaneNOD** [yegorf1/RogueBot#105]

**Comment by YogurtTheHorse** [comment]
Я вообще не понимаю, что не так с Лепреконом.
Он почему-то открывает другую комнату.
Как? Почему?
Не знаю

**Comment by KaneNOD** [comment]
Лепрекон открывает только те комнаты, которые в миссиях, в другие он не лезет

**Comment by YogurtTheHorse** [comment]
Да, но почему название одной комнаты, а контент другой?

**Comment by YogurtTheHorse** [comment]
Короче жесть какая-то

**Comment by KaneNOD** [comment]
в каких файлах расписаны миссии?
причём, проблема не появилась сразу. изначально было все нормально, после какого-то из фиксов лепрекон стал так делать

**Comment by YogurtTheHorse** [comment]
В missions/ 
rooms/missions 
user/missions_defenition.py

**Comment by KaneNOD** [comment]
[лог терминала+переписка бота.zip](https://github.com/yegorf1/RogueBot/files/470664/default.zip)
