### ISSUE TITLE
Тарговля биз стукав

### ISSUE THREAD

**Issue by arstoncas** [yegorf1/RogueBot#106]
Вы открываете дверь и видите... 
Торговца?... 
Перед вами находится какая-то будка, неумело сколоченная из каких-то кривых досок.
За широкой деревянной доской (прилавок) на воображаемой табуретке сидит зеленый бугай метра 2 ростом. Серьезно, он сидит в воздузе!
Завидев вас, он что-то нечленораздельно говорит, вы понимаете лишь: 
"Привит, юдишка! Йа есть Боба! Босс сказал Бобе таргавать!! Боба типерь умеет в тарговлю!"

Ненене, все хрень, вот торговля: 
1ый товар 
Зуб (цена 1 зуб)
Аписание: Тока што выбил с "рандом имя игрока", дажи кечтуп ищо капаит! 
2ой товар 
Палка ((на самом деле это посох мага)) (цена 100 зубов)
Плахая палка, адной такой стукнул юдишку - а она сламалась 

3ий товар 
Парашок ((на самом деле протеин)) (цена 100 зубов)
Вкусный парашок, клянусь Горком и Морком!

**Comment by KaneNOD** [comment]
при оформлении указываются лэйблы
