### ISSUE TITLE
Миссии на оружие?

### ISSUE THREAD

**Issue by mibobkov** [yegorf1/RogueBot#110]
Есть предложение выдавать оружие постепенно. Чтобы нельзя было получить в первой же комнате вилку (или какое сейчас самое лучшее оружие?) и дальше просто ходить всех убивать.

**Comment by KaneNOD** [comment]
в так называемом энд-гейме это не сыграет никакой роли, а в начале  игры всё более-менее нормально, на мой взгляд.

**Comment by YogurtTheHorse** [comment]
Соглашусь с @Teogor
