### ISSUE TITLE
Нерф армии и небольшие правки

### ISSUE THREAD

**Issue by KaneNOD** [yegorf1/RogueBot#118]
- Уменьшить количество золота.
- Сделать армию реже чем сейчас.
- При победе пригонять караван

**Comment by kuleshov-aleksei** [comment]
Мне кажется сделать появление армии реже самый оптимальный вариант, сейчас слишком легко на них фармить золото
Сделать сильнее не вариант, их легко победить, просто времени потребуется больше. Поднимать урон тоже не очень, это очень обидная смерть, особенно после нескольких дней игры.

**Comment by YogurtTheHorse** [comment]
Есть вариант сделать ее реже (как и сказал @Encamy) и голды поменьше

**Comment by KaneNOD** [comment]
Я предлагаю сделать ее раз в 150 комнат и порезать золото на 30%

**Comment by YogurtTheHorse** [comment]
Оформил на себя, сделаю еще пару фич
