### ISSUE TITLE
Подключить MongoDB

### ISSUE THREAD

**Issue by thekiba** [yegorf1/RogueBot#131]
# Проблема

На данный момент использование TinyDB не оправдывает ожидания. База данных раздулась и python уже не справляется с этой нагрузкой.
# Решение

Необходимо подключить MongoDB или любую другую базу данных.

**Comment by YogurtTheHorse** [comment]
Сегодня тогда подниму монго
Не знаю как переносить базу

**Comment by thekiba** [comment]
Чтобы перенести базу нужно написать миграцию, которая будет обращаться к текущей базе, считывать конкретные сущности и записывать их в Mongo.
