### ISSUE TITLE
Исключить не предусмотренные ранее сценарии абуза сделки

### ISSUE THREAD

**Issue by KaneNOD** [yegorf1/RogueBot#134]
```
- Запрет на казино
- По окончании забирать всё золото(если было)
```

**Comment by YogurtTheHorse** [comment]
Как-то жестко)

**Comment by YogurtTheHorse** [comment]
Запрет на казино тоже не имеет смысла. Там больше проигрывают

**Comment by YogurtTheHorse** [comment]
А забирать золото это как-то не оч
Лучше тогда вообще не давать бабло, а то выходит глупо

**Comment by KaneNOD** [comment]
в большинстве случаев сделка - все равно смерть)
