### ISSUE TITLE
Фильтрация ников

### ISSUE THREAD

**Issue by thekiba** [yegorf1/RogueBot#163]
## Проблема

Некоторые игроки используют матерные ники.
## Решение

Добавить фильтрацию ников по словарю матерных слов.
Давать создать персонажа с матерным ником, но не отображать его в топе и в предложении имен.

**Comment by Fadds** [comment]
Реализовать этот механизм:
[content_script.js](https://github.com/oshibka404/antimat/blob/master/Source/content_script.js)

**Comment by YogurtTheHorse** [comment]
Мне нравится вариант с затменной матов х)
