### ISSUE TITLE
Выбор имени пета

### ISSUE THREAD

**Issue by Yashko** [yegorf1/RogueBot#164]
Отличный выбор. Наверное.. Я свою дочь вообще назвал **none**. Нет у меня вкуса

строка - 
https://github.com/yegorf1/RogueBot/blob/0b52427bb72aebd1a61e9e8c048b68dedd4b53d7/user/pets_defenition.py#L34

**Comment by thekiba** [comment]
А в чем проблема?

**Comment by Yashko** [comment]
Так и должно быть "none"?

**Comment by thekiba** [comment]
Видимо кто-то ник такой сделал :)

**Comment by Fadds** [comment]
Часто такое вижу. Возможно, стоит глянуть, что выводит

```
def random_user():
    return get_user(random.choice(list(get_telegram_users())))
```

**Comment by YogurtTheHorse** [comment]
Это пофиксится в #163
