### ISSUE TITLE
Номер чека в Фискальном чеке

### ISSUE THREAD

**Issue by thekiba** [yegorf1/RogueBot#168]
Добавить номер чека в Фискальном чеке.

**Comment by KaneNOD** [comment]
рандомный генератор, или по порядку?

**Comment by YogurtTheHorse** [comment]
Там в чеке написано количество штук 
И оно всегда равно единице, а зелья продаются по две штуки

**Comment by KaneNOD** [comment]
Егор, тут немного не об этом речь)

**Comment by thekiba** [comment]
> рандомный генератор, или по порядку?

По порядку, конечно же :)
