### ISSUE TITLE
Доработка Доктора

### ISSUE THREAD

**Issue by Fadds** [yegorf1/RogueBot#171]
1. После убийства Доктора, вместо формулы`HP*2^i` (i-1 — счётчик смертей Д.), применять формулу `HP*1.5^i` (i-1 — счётчик смертей Д.);
2. Запретить игроку новый заход к Д., если он является его последним убийцей;
3. После убийства Д., выдать предмет #172.

**Comment by Fadds** [comment]
И, видимо, после обновления, стоит сбросить счётчик убийств.

**Comment by KaneNOD** [comment]
многовато
лучше после каждой смерти хп поднимать по 1%
и начинать с небольшого значения

**Comment by Fadds** [comment]
Лидерборд будет засран на сотни строк
Тогда давайте хоть по 
`HP*1.1^i`
