### ISSUE TITLE
Лазерная отвёртка: модификация

### ISSUE THREAD

**Issue by Fadds** [yegorf1/RogueBot#172]
В связи с #171, изменить характеристики предмета на следующие:
- Наличие в предмета в инвентаре:
- \- HP, INT, STR: +20%
- \- +10 HP каждый ход
- В случае, если владелец предмета перестаёт быть последним убийцей Доктора, предмет исчезает.

**Comment by KaneNOD** [comment]
Я против. Это придёт к тому, что появится один какой-то игрок, который будет бессмертен, так как у него будет зашкаливающее количество здоровья.

**Comment by thekiba** [comment]
Я так понимаю, что HP просто будет регениться каждый ход, @Fadds?

**Comment by Fadds** [comment]
Да, хп только регенится до максимума.

Я же вчера выступал как сторонник ограничения макс. хп, а тут раздаю порог налево-направо?)

**Comment by Fadds** [comment]
Да, именно так. Небольшой хил.

**Comment by Fadds** [comment]
Сделали?
