### ISSUE TITLE
Чёрно-белое зелье.

### ISSUE THREAD

**Issue by Fadds** [yegorf1/RogueBot#183]
Свойства: меняет местами значения НР и МР.

**Comment by Fadds** [comment]
Что с этим делать? В каких случаях может получиться, что МР<0 ?
![image](https://cloud.githubusercontent.com/assets/10957226/18633560/92d01be0-7e85-11e6-83be-da410fe237d1.png)

**Comment by YogurtTheHorse** [comment]
> Что с этим делать? В каких случаях может получиться, что МР<0 ?

Такого не бывает (:

**Comment by Fadds** [comment]
А чего тогда Киба панику наводит?

**Comment by thekiba** [comment]
Где я навожу? Это были шуточки :D

**Comment by YogurtTheHorse** [comment]
Просто :)

**Comment by Fadds** [comment]
![image](https://cloud.githubusercontent.com/assets/10957226/18633729/6e961bb6-7e86-11e6-8156-b6d740b44905.png)

**Comment by YogurtTheHorse** [comment]
Зачем ты открыл, @Fadds ?
