### ISSUE TITLE
Ошибка отображения имени у Торговца

### ISSUE THREAD

**Issue by kaldai** [yegorf1/RogueBot#187]
Просто текст, вместо рандомного имени игрока
"Тока што выбил с {0}, дажи кечтуп ищо капаит!"

**Comment by Fadds** [comment]
Исправлено

**Comment by kaldai** [comment]
пулл реквест закрыть?

**Comment by thekiba** [comment]
> Исправлено

Где исправлено? Скинь ссылку на pull-request
