### ISSUE TITLE
Не использовалось зелье

### ISSUE THREAD

**Issue by thekiba** [yegorf1/RogueBot#195]
<img width="810" alt="screen shot 2016-09-20 at 01 09 37" src="https://cloud.githubusercontent.com/assets/1910515/18651946/dead7ba4-7ece-11e6-85b2-ea4453d14d23.png">

**Comment by KaneNOD** [comment]
Баг скорее в том, что игроку не всегда присылается полный текст от бота

**Comment by YogurtTheHorse** [comment]
#139
