### ISSUE TITLE
Установить предел характеристик(updated)

### ISSUE THREAD

**Issue by KaneNOD** [yegorf1/RogueBot#199]
> Наверное меня не так поняли. Я не хочу делать хардкап характеристик игрока, после которого набор характеристик уже не возможен.
### Что именно я предлагаю.
- **Ввести предел характеристик, которые можно получить с предметов.**
- Максимальный запас здоровья `550`(Его я предлагаю сделать пределом, который нельзя увеличить)
- Сами характеристики:
  - Сила `3000`
  - Интеллект `3000`
  - Защита `500`
  - Харизма `800`
- Предел золота, которое может одновременно находиться у игрока равен `5,000,000`
- Если игрок получил с предметов данные максимумы, он всё еще может увеличивать эти характеристики, но за более высокую стоимость и не при помощи предметов.

**Comment by Fadds** [comment]
Нет, это нужно решать грамотным распределением статов предметов, чтобы предел образовался сам по себе.

**Comment by YogurtTheHorse** [comment]
Closed with #208
