### ISSUE TITLE
Сбавить градус сложности.

### ISSUE THREAD

**Issue by KaneNOD** [yegorf1/RogueBot#203]
Description coming soon™

**Comment by Fadds** [comment]
Удаляй, пока Егор не увидел)

**Comment by KaneNOD** [comment]
Зачем?
Я еще даже не изложил суть)

**Comment by YogurtTheHorse** [comment]
Удаляй, тебе говорят же :D

**Comment by thekiba** [comment]
Закрываем?

**Comment by KaneNOD** [comment]
я против, идея еще не изложена.

**Comment by YogurtTheHorse** [comment]
Влад седня что-то расскажет

**Comment by KaneNOD** [comment]
временно закрыто.
