### ISSUE TITLE
Статистика

### ISSUE THREAD

**Issue by Fadds** [yegorf1/RogueBot#204]
Для более полного понимания нужд игроков и балансировки, нужно следующее. 
- Реализовать счетчик нажатий на каждую кнопку. Нажатия кнопок старше 24 часов не учитываются.
- По команде /stats, на каждой кнопке в скобках выводится её счетчик: [Аллах (322)]
- Обозначать комнату в которой была нажата кнопка

**Comment by YogurtTheHorse** [comment]
Сделал
