### ISSUE TITLE
Потолок статов

### ISSUE THREAD

**Issue by Fadds** [yegorf1/RogueBot#208]
### Задача:

Необходимо изящно ввести порог статов.
### Решение:

Расчёт статов, которые даёт предмет производится по формуле:
![image](https://cloud.githubusercontent.com/assets/10957226/18723582/d558b784-8041-11e6-887e-d3169fe03489.png)

S — статы, которые даёт предмет
N — порядковый номер предмета в стаке одинаковых предметов

График эффективности предмета:
![image](https://cloud.githubusercontent.com/assets/10957226/18686092/5790e498-7f83-11e6-9785-9b8533f1da3f.png)
![image](https://cloud.githubusercontent.com/assets/10957226/18686285/155a0950-7f84-11e6-9158-176a72d3fb11.png)

График общего развития статов будет выглядеть примерно так:
![image](https://cloud.githubusercontent.com/assets/10957226/18687242/d4290a0e-7f87-11e6-87e7-c91fddbc1b66.png)

Только не перепутайте: не S **каждого** предмета из стака одинаково уменьшается в зависимости от количества предметов, а **уменьшается S каждого следующего** предмета, в зависимости от его позиции в стаке.

**Comment by YogurtTheHorse** [comment]
Можно формулу стата для Н предметов?

**Comment by thekiba** [comment]
`DAMAGE` - атака оружия
`K = 0,79` - коефициент
`N` - количество предметов

`DAMAGE + DAMAGE * (1/K) * ln(N)`

Ведет себя похожим образом

**Comment by KaneNOD** [comment]
Допустим у нас есть некий игрок. его харатеристики:

> Сила 0
> урон от удара рукой равен 10.

Теперь мы прибавим игроку 100 силы и получим

> Сила 100
> урон от удара рукой равен 20.

**Таким образом мы получаем что 1 силы = 1% увеличения урона от атаки.**

**Comment by Fadds** [comment]
Киба, у меня плохие новости:
![image](https://cloud.githubusercontent.com/assets/10957226/18690062/f4023df2-7f94-11e6-9997-0569bc7e32e0.png)
Работает наоборот

**Comment by thekiba** [comment]
Решили, используем для предметов:

`DAMAGE` - атака оружия
`K = 0,79` - коефициент
`N` - количество предметов

`DAMAGE + DAMAGE * ( 1 / K ) * ln( N )`

Данная формула должна использоваться для расчета всех статов, а именно Сила, Интелект, Защита.

**Comment by thekiba** [comment]
Формула для расчета нанесенного урона:

`DAMAGE * (1 - ( DEFENCE / ( 300 + DEFENCE ) ) )`

`DAMAGE` - атака монстра
`DEFENCE` - защита игрока

Данная формула должна использоваться так же при атаке монстра игроком.
