### ISSUE TITLE
Казино: ограничение максимальной ставки

### ISSUE THREAD

**Issue by Fadds** [yegorf1/RogueBot#219]
Чтобы в будущем, когда взаимодействие игроков будет более многосторонним, не подрывать "мировую" экономику, стоит понерфить источники "шальных денег": казино (возможно, забыл что-то ещё). Ограничить макимальную ставку до 10,000 (давайте обсудим цифры).

**Comment by thekiba** [comment]
А есть смысл ограничивать?

Казино изначально игра в одну сторону -- выигрывает диллер.
Для игрока всегда мат ожидание отрицательное.

**Comment by Fadds** [comment]
Кто-нибудь может завалить 1кк на зеро, выиграть, и отдать в казну фракции. И фракция потом будет доминировать месяц за счёт этих денег.

**Comment by thekiba** [comment]
Рассматривать рулетку как единичный случай неправильно. 

Один выиграет 14 миллионов, значит другие проиграют 15 миллионов. Это рулетка.

**Comment by YogurtTheHorse** [comment]
Согласен с Кибой, сейчас все вполне ок (:

**Comment by Fadds** [comment]
Считаю, что как раз неправильно — не рассматривать единичные случаи. 
Опасно хотя бы допускать ситуации, где есть вероятность того, что у конкретного игрока может оказаться много денег (ну это ладно, накрабил — молодец), которые он ещё и может умножить х14. 
И как раз, он выиграет 15 миллионов, а кто-нибудь, желающий сделать то же самое, из другой фракции проиграет. В результате сильный дизбаланс, одна фракция при деньгах, другая в ~~жопе~~ упадке.

**Comment by YogurtTheHorse** [comment]
Ну так пусть Фракции будут ответственными
Все как в _Жизни_
