### ISSUE TITLE
Застревание с кубиком

### ISSUE THREAD

**Issue by thekiba** [yegorf1/RogueBot#229]
# Лог чата

![226613901_13903395287961422806](https://cloud.githubusercontent.com/assets/1910515/18785531/fb498862-8198-11e6-8ed4-734dd79a4f8b.jpg)

![225519431_1403166256398677374](https://cloud.githubusercontent.com/assets/1910515/18785537/ffd1fb44-8198-11e6-878b-06ea47a7ff19.jpg)

![225522889_7935418677629842442](https://cloud.githubusercontent.com/assets/1910515/18785539/029db656-8199-11e6-9725-30ce5aafae4c.jpg)

![226617810_4775083296176280705](https://cloud.githubusercontent.com/assets/1910515/18785541/056c3f88-8199-11e6-8cad-577d09d74123.jpg)

![225515112_1502996691126815632](https://cloud.githubusercontent.com/assets/1910515/18785544/084c5c2e-8199-11e6-86ce-fa34bbb228aa.jpg)

**Comment by thekiba** [comment]
# Debug

![225515086_5378469474816763143](https://cloud.githubusercontent.com/assets/1910515/18785553/1a7fac70-8199-11e6-83be-713292f8f614.jpg)

![226614320_4663350734534266382](https://cloud.githubusercontent.com/assets/1910515/18785555/1cfbf378-8199-11e6-8b57-d10f851782d8.jpg)

**Comment by YogurtTheHorse** [comment]
Получилось повторить?

**Comment by thekiba** [comment]
Я не пробовал)

**Comment by YogurtTheHorse** [comment]
Не повторялось
