### ISSUE TITLE
Граната

### ISSUE THREAD

**Issue by YogurtTheHorse** [yegorf1/RogueBot#248]
Взрывает монстра, но возможно и тебя заденет

**Comment by Fadds** [comment]
Descr: _Эффектно подрывает противника. Может задеть и тебя, если недобросишь. Не забудь выдернуть чеку._
В бою:
- Бросить гранату
  - если `triggeredGrenadesCount < 1`:
    - Сообщение: `Ты швыряешь гранату в противника, падаешь прикрывая голову руками и ждёшь... Ждёшь... Ничего не происходит! Где взрыв?\n*Идиот, нужно было выдернуть чеку!*`
    - -1 предмет
  - если `triggeredGrenadesCount > 0`:
    - `throw = %DICE%+(%STR%/50)`
    - `mobDamage = grenadeDamage+throw*2`
    - `selfDamage = 100-throw*3` (следите за отрицательными значениями)
    - Сообщение: `Ты швыряешь гранату в противника, падаешь прикрывая голову руками и ждёшь... Ждёшь...\nТак себе бросок, %throw% метров. Салага.\nПротивник получил %mobDamage% урона. Тебя тоже немного задело осколками на %selfDamage%.` 
    - -1 предмет
- Выдернуть чеку из гранаты
  - `triggeredGrenadesCount += 1`
  - `explode = %CURRENT_TIME% + 10 секунд`
  - Сообщение: `Чека — в зубах, граната — в руке!`
  - таймер по `explode`: если граната выбрасывается, таймер сбрасывается, если к наступлению `explode` граната не выброшена — смерть, сообщение: `Дёрнул чеку и бросай! Бросай!\_Гранатам, обычно, не нравится, когда из них что-нибудь выдёргивают и они в буквально *взрываются* от обиды. В следующий раз бросай её подальше._`
  - Реализовать возможность выдернуть чеку сразу из нескольких гранат.

`grenadeDamage = ???`

**Comment by thekiba** [comment]
Только без `throw`, пожалуйста :)

**Comment by Fadds** [comment]
А что не так?

**Comment by thekiba** [comment]
На счет python не знаю, но в некоторых других ЯП зарезервированное слово и используется для того, чтобы бросить исключение. 

Поэтому в данном контексте оно сбивает с толку.  

Поэтому не надо `throw` :)

**Comment by Fadds** [comment]
Да это мелочи.
