### ISSUE TITLE
Армия Вьетнамцев

### ISSUE THREAD

**Issue by YogurtTheHorse** [yegorf1/RogueBot#249]
Огромая куча Вьетнамцев на СССРских летающий тракторов, которая устроит дискотеку с фейерверком и не только
Большой урон
Лут: пара гранат, АК

**Comment by Fadds** [comment]
Огромая куча вьетнамцев, на летающих тракторах производства СССР, устроит дискотеку с фейерверком и светомузыкой. 
Большой урон
Лут: пара гранат, АК
