### ISSUE TITLE
Баг с зельями

### ISSUE THREAD

**Issue by KaneNOD** [yegorf1/RogueBot#262]
_Два и больше разных зелий могут принять один и тот же цвет_

**Comment by YogurtTheHorse** [comment]
Пруфы

**Comment by KaneNOD** [comment]
а разве в коде этот сценарий предусмотрен? я не увидел

**Comment by YogurtTheHorse** [comment]
Я вдруг осознал, что дело в том, что люди пили зелье дальтонизма!
