### ISSUE TITLE
Продолжение с checkpoint?

### ISSUE THREAD

**Issue by tarampampam** [yegorf1/RogueBot#269]
После применения свитка сохранения и дальнейшей смерти не происходит возобновления с места сохранения. Так и должно быть?

![2016-12-18 13-52-01](https://cloud.githubusercontent.com/assets/7326800/21292492/6fc86afe-c529-11e6-8ea7-321b41427a9e.png)

При старте новой сессии отсутствует проверка на `if user.get_variable('was_checkpoint', def_val=False) is True:`, или я что-то упустил в логике?

**Comment by YogurtTheHorse** [comment]
Свиток сохранения работает немного не так. 
После смерти персонажа вместо смерти отправляет в коридор
