### ISSUE TITLE
mystery_book_2?

### ISSUE THREAD

**Issue by tarampampam** [yegorf1/RogueBot#270]
Каким образом возможно получить `mystery_book_2`?

Для этого нужно чтоб у Гидеона выполнилось условие `if result > DICE_MAX` - но с помощью чего можно этого добиться?

**Comment by YogurtTheHorse** [comment]
@tarampampam С помощью артефактов (:

**Comment by tarampampam** [comment]
А каких? :)

**Comment by YogurtTheHorse** [comment]
@tarampampam Например Монетка

**Comment by tarampampam** [comment]
Дает бонус в 1 с вероятностью 1:10, плюс надо чтоб выпало 32 изначально. То есть вероятность этого составляет 29 *(выпадает же от 3 до 32?)* на 10, что равно 1:290? Учитывая что комната Гидеона выпадает один раз на примерно 25 итераций - не слишком ли сложен квест?

**Comment by YogurtTheHorse** [comment]
@tarampampam Это же не единственный артефакт такой артефакт 
Их множество, плюс монеток может быть много

**Comment by tarampampam** [comment]
Пускай вероятность выпадения > 32 будет даже 1:30 - комната гидеона в любом случае выпадает довольно таки редко. Может немного повысить вероятность всё-таки?

**Comment by YogurtTheHorse** [comment]
@tarampampam Да нет, меня все устраивает (:

**Comment by tarampampam** [comment]
Считай - в комнату с Гидеоном можем попасть в среднем один раз в 25 минут *(проверил эмпирически только-что)*.

Надеюсь, я доступно объясняю, и не сильно ошибаюсь в расчетах?

**Comment by thekiba** [comment]
Мы тебя прекрасно поняли, но в расчетах ошибка.

Бросается 4 кости по 8 значений на каждой. Суммарное значение от 4 до 32 и здесь нормальное распределение.

И как сказал Егор, монеток может быть много и они не единственные предметы, которые добавляют бонус с костям.

**Comment by tarampampam** [comment]
Тогда помогите рассчитать вероятность выпадения значения > 32? Что-то я не совсем понимаю как работает механизм dice

**Comment by YogurtTheHorse** [comment]
@tarampampam Симулируется бросок 4 костей с восмью гранями, загляните в user.throw_dice

**Comment by thekiba** [comment]
@tarampampam точные вероятности для 4d8

<img width="161" alt="screenshot 2016-12-19 23 33 13" src="https://cloud.githubusercontent.com/assets/1910515/21328134/8b377648-c643-11e6-8241-3be9bf33c0fa.png">

И ссылка, если интересно поиграться http://anydice.com/

**Comment by tarampampam** [comment]
Так, вероятность выпадения восьмерки на одной кости - 1:8. Костей - четыре, общая вероятность 1:8*4 = 1:32 соответственно. Есть бонус в виде кубика с единичкой и монетки. Кубик дает `-1` к вероятности, одна монетка - `-0,1`.
Допустим, у нас 15 монет и кубик, суммарный бонус `-2,5`, и не смотря на это - общая вероятность 1:29,5 соответственно.

Напомню, что комната Гидеона выпадает в среднем раз в 20 минут (точнее считать прямо сейчас нет желания, к сожалению; может и раз в 40, а может и через 15 минут).

20 минут множим на 30 попыток, получаем 600 минут, или 10 часов целенаправленного подбора. Правда - не слишком ли это? Ради 4k голды или +20hp?

В любом случае - не считайте это критикой или камнем в огород, скорее простое рассуждение о.. балансе?

**Comment by thekiba** [comment]
@tarampampam, если интересует вероятность выпадения 33 при 4 костях с 8 гранями и монеткой, то:

1. Ищем общее количество исходов 8^4*10 = 40960
2. Нас интересует только один исход, когда все кости дадут результат 8, а монетка 1, следовательно вероятность 1/40960.
3. Гидеон выпадает раз в 20 минут, умножаем на 40960 и получаем 13653 часа.
4. В среднем рабочее время человека 164 часа в месяц, 13653 делим на 164 и получаем 83 месяца или почти 7 лет рабочего времени.

Если интересует реальная возможность получить вторую книгу, то необходимо накопить 18 игральных костей рассказчика или 180 монеток. Тогда вероятность выигрыша у Гидеона будет равна 50%.

**Comment by YogurtTheHorse** [comment]
@thekiba Ну и норм вероятность (:

**Comment by thekiba** [comment]
@yegorf1, меня тоже все устраивает :)

**Comment by tarampampam** [comment]
Чет я на ночь глядя совсем бестолково считаю. Вероятность зачетная

**Comment by YogurtTheHorse** [comment]
@tarampampam То-то и оно
