### ISSUE TITLE
После чекпоинта количество конфет замораживается

### ISSUE THREAD

**Issue by behemon** [yegorf1/RogueBot#275]
После чекпойнта количество конфеток заморожено, продавать или есть их можно, но они не расходуются

**Comment by YogurtTheHorse** [comment]
@behemon Давай ты для начала будешь делать нормальные баг репорты, а не писать все в заголовке

**Comment by behemon** [comment]
log :

В инвентаре ты нашел:
Шапочка из фольги (30 шт. ценой 1400 злт.) :
Головной убор из металлической фольги, якобы способный защитить мозг и сознание от вредных излучений и влияний.

**Конфетка (3 шт. ценой 1 злт.) :**
Сладкая и вкусная

Балетная пачка (5 шт. ценой 210 злт.) :
Миленькая и беленькая.

Винцо (424 шт. ценой 210 злт.) :
Бутылка отличного вина. Немного испачкана в иле. Божественный вкус.

Серебрянная ложка (1 шт. ценой 2 злт.) :
Её не существует. Не сгибать!
[1:44:40 PM] Alexy:
**:moneybag: Продать Конфетка**

[1:43:22 PM] RogueBot:
Золотишко-то.. Звенит!

В инвентаре ты нашел:
Шапочка из фольги (30 шт. ценой 1400 злт.) :
Головной убор из металлической фольги, якобы способный защитить мозг и сознание от вредных излучений и влияний.

**Конфетка (3 шт. ценой 1 злт.) :**
Сладкая и вкусная

Балетная пачка (5 шт. ценой 210 злт.) :
Миленькая и беленькая.

Винцо (424 шт. ценой 210 злт.) :
Бутылка отличного вина. Немного испачкана в иле. Божественный вкус.

Серебрянная ложка (1 шт. ценой 2 злт.) :
Её не существует. Не сгибать!

**Comment by YogurtTheHorse** [comment]
Это #236
