### ISSUE TITLE
Книга

### ISSUE THREAD

**Issue by YogurtTheHorse** [yegorf1/RogueBot#65]
Комната с книгой судьбы. Страницы, которые читаются подряд. Есть выбор, читать первую, вторую, последнюю страницу, уйти. Прочёл последнюю - умер.

**Comment by YogurtTheHorse** [comment]
[Uploading RogBot_Q3_Book.pdf…](Книжка)

**Comment by KaneNOD** [comment]
В пулл-реквесте.
