### ISSUE TITLE
Свиток побега

### ISSUE THREAD

**Issue by YogurtTheHorse** [yegorf1/RogueBot#66]
Позволяет сбежать из любого боя. При этом вы теряете 50% золота в инвентаре и, возможно, случайную вещь

**Comment by KaneNOD** [comment]
Егор, уверен насчет этого свитка?

**Comment by YogurtTheHorse** [comment]
Пусть стоит 2к

**Comment by YogurtTheHorse** [comment]
Лут от него не получаешь
