### ISSUE TITLE
Леприкон

### ISSUE THREAD

**Issue by YogurtTheHorse** [yegorf1/RogueBot#70]
Минимальный урон: 25
Фраза на входе: Вы входите на полянку, устланную четырехлистными клеверами. В центре стоит горшочек, полный золота. Что это над ним? Радуга ? Откуда она, черт возьми в подземелье ? Хотя какая разница, когда перед тобой столько золота! /тут два варианта - уйти или взять золото (250 монет). Если игрок берет золото, то черн 5- 10 открытых дверей встречает Леприкона, который требует вернуть 1000 монет. В случае отказа - нападает на игрока/
Жизней: 1500
Максимальный урон: 50
Лут: Четырехлистный клевер (повышает удачу/харизма на 1)

**Comment by KaneNOD** [comment]
ага и горшочек фиктивного золота, который при использовании на бандитов с шансом 0.05 отвлекает их

**Comment by YogurtTheHorse** [comment]
Шанс мелкий)
Лучше 0.2

**Comment by KaneNOD** [comment]
Принято
