### ISSUE TITLE
EL DIABLO

### ISSUE THREAD

**Issue by KaneNOD** [yegorf1/RogueBot#74]
дьявол
ты видишь просторную комнату. в углу потрескивает камин, на стенах развешаны охотничьи трофеи....

**Comment by thekiba** [comment]
Опиши хоть Diablo :)

**Comment by Teogor** [comment]
если примерно, там будет возможность выбрать что-то и после выбора у игрока останется 7 ходов до смерти по контракту. об этом условии контракта сообщается как обычно. после заключения
