### ISSUE TITLE
Комната Казино

### ISSUE THREAD

**Issue by KaneNOD** [yegorf1/RogueBot#93]
Количество цветов: 13
Зеленых: 1
Красных: 6
Черных: 6

Номера
Зеленые: 0
Красные: 2, 4, 6, 8, 10, 12
Черные: 1, 3, 5, 7, 9, 11

Вероятности
Зеленые: 8%
Красные: 46%
Черные: 46%

Коеффициент:
Зеленые: x12
Красные: x2
Черные: x2

Ставка 100-500 голд.

За подсчеты спасибо @thekiba

**Comment by thekiba** [comment]
По поводу вероятностей. Используй метод https://docs.python.org/2/library/random.html#random.randrange для получения номера раунда. 

Номера цветов я тоже писал, поищи в чате. Если не найдешь, то я еще раз напишу.
